### ISSUE TITLE
Missing README in repo

### ISSUE THREAD

**Issue by jahway603** [raspberrypi-ui/raspberrypi-ui-mods#2]
Missing README in repo explaining what this project is and what it does.

**Comment by spl237** [comment]
The name of the repository is an adequate description of what it contains - Raspberry Pi user interface modifications.

**Comment by jahway603** [comment]
What's the LICENSE this is released under? What are more details to go in the README created as PR https://github.com/raspberrypi-ui/raspberrypi-ui-mods/pull/3 ?

**Comment by spl237** [comment]
This package has existed for almost a decade without a README file, because it does not need one. And it does not require licensing terms, as there is no code therein; just configuration files.
