### ISSUE TITLE
PiX/PiXflat/PiXNoir and large themes "max_hover_toggled" issue

### ISSUE THREAD

**Issue by b1ack0p** [raspberrypi-ui/raspberrypi-ui-mods#5]
Hi,

Dont know who is managing PiXflat themes in this repo > http://archive.raspberrypi.org/debian/pool/main/p/pixflat-theme/ but I realized "_hover_" effect doesnt work for "_max_hover_toggled.xbm_" and "_max_hover_toggled_l.xbm_" items on window. "_hover_" and "_toggled_" should be replaced in the name of xbm files in "_/themes/PiX*/openbox-3/_" to get hover effect working. like this > "_max_toggled_hover.xbm_" and "_max_toggled_l_hover.xbm_"

**Comment by spl237** [comment]
That version of the icon names works in both openbox and wayfire; some other window managers do have the names inverted, but this is the correct way around for those we use.

**Comment by b1ack0p** [comment]
Oh i see now. I was using theme on native Debian/LXDE/openbox.

**Comment by b1ack0p** [comment]
but you mentioned it works in openbox but why not in native LXDE/openbox for me?

**Comment by spl237** [comment]
Openbox changed the way these are ordered at some point - it sounds as if you are using an older or newer version than ours.

**Comment by b1ack0p** [comment]
Debian 12 Stable is using Openbox v3.6.1-10. Yea maybe my version doesnt support that naming. not a big deal as long as it works for original repo.
