### ISSUE TITLE
pi-greeter files in ui-mods

### ISSUE THREAD

**Issue by nbuchwitz** [raspberrypi-ui/raspberrypi-ui-mods#6]
While digging into some pi-greeter related stuff I've stumbled over the pi-greeter files for labwc and waywire in `/usr/share/xgreeters`, which are not part of the `pi-greeter` package. Is there a special reason for this? The openbox file is part of the `pi-greeter` repo though.

**Comment by spl237** [comment]
Before you get too involved in this, I should say that I think it is unlikely we will accept the changes you are proposing to the way the greeter is configured.

There is no fundamental advantage to us in making these changes - they only benefit people who wish to customise our OS. Furthermore, these changes will require in-field updates which change files in the /etc directory, which means that on an update via apt, the user will be asked a not-terribly-helpful question about which version to use, and in our graphical update tools that can't even happen and unexpected behaviour may therefore result. Plus our configuration tools edit the greeter config file in /etc, so those will all also need to be updated - we would be looking at a lot of changes in various places with the associated testing overhead and chance of things breaking - and as said above, none of these changes offer any advantage to us over what we have now.

So I'm sorry, but if you want to customise the greeter, I think you'll need to do it locally in your image - I'd suggest forking the pi-greeter package itself and changing its defaults to your needs. Either way, you are going to need to customise your display manager.
