### ISSUE TITLE
/usr/bin/lwrespawn

### ISSUE THREAD

**Issue by jth5557** [raspberrypi-ui/raspberrypi-ui-mods#8]
Can /usr/bin/lwrespawn function correctly without adding the -f option to pgrep in line 2?

if pgrep $1 > /dev/null ; then

I get the following message when using $1 arg longer than 15 characters:

pgrep: pattern that searches for process name longer than 15 characters will result in zero matches
Try `pgrep -f' option to match against the complete command line.

In all the uses I see of lwrespawn the $1 argument would be over 15 characters, from /etc/xdg/labwc/autostart:
 
/usr/bin/lwrespawn /usr/bin/pcmanfm --desktop --profile LXDE-pi &
/usr/bin/lwrespawn /usr/bin/wf-panel-pi &

**Comment by spl237** [comment]
Are you saying that something actually doesn't work? I'm not sure what actual problem you are raising?

lwrespawn works as intended in the way we use it, so I can't see any sign of an actual bug.

**Comment by jth5557** [comment]
Can lwrespawn be used to start a process  with a path less than 15 characters?  In a raspberry running as a kiosk application for instance?  Or is lwrespawn only intended for the desktop processes of labwc?

When I run a kiosk app from labwc/autostart and the path of the app I would like to start is less than 15 chars lwrespawn doesn't launch the app.  I either need to lengthen the path, or edit lwrespawn line 2 to 'pgrep -f $*' instead of 'pgrep $1'.

If it's working for your intended use I can accept that, I just find it's behavior unusual and maybe not as you intended.  

I also found other instances of complaints about the 15 char operation of pgrep.  For now I am going to make my own kiosk respawn script and watch for updates to pgrep that may alter it's function.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037450
