### ISSUE TITLE
dpkg configure is broken when there is a user without identically-named group

### ISSUE THREAD

**Issue by michaellass** [raspberrypi-ui/raspberrypi-ui-mods#9]
79fef1dd315e6b094023c55575ab636ec345f9eb introduced the following regression:

If a user exists, has a valid login shell set but there is no group with the same name, dpkg will fail configuring raspberrypi-ui-mods 1.20241130:

```
Setting up raspberrypi-ui-mods (1.20241130) ...
chown: invalid group: 'dht22:dht22'
dpkg: error processing package raspberrypi-ui-mods (--configure):
 installed raspberrypi-ui-mods package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 raspberrypi-ui-mods
```
(The user is named `dht22` in that example)

A workaround is to temporarily set the shell of those users to something invalid, configure the package, and change the shell back afterwards:
```
% usermod -s /bin/false dht22
% dpkg --configure -a
Setting up raspberrypi-ui-mods (1.20241130) ...
% usermod -s /bin/bash dht22
```

**Comment by spl237** [comment]
Shoud be fixed in the next update - I've modified so that it associates the file for each user with that user's login group, rather than assuming the name is the same.
